<?php

/**
 * @file
 * Contains lagoon_varnish.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lagoon_varnish_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lagoon_varnish module.
    case 'help.page.lagoon_varnish':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A meta-module that bundles and configures Varnish cache clearing for the Lagoon platform') . '</p>';
      return $output;

    default:
  }
}
